### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FlamptX** [Chaxiraxi/Discord-Token-Grabber#1]
It didn't work because of an error: cannot read property replace of undefined. Please help.

**Comment by Chaxiraxi** [comment]
Hi, and sorry for answering a bit late.
I can't see how do you get this error, and the script is correctly working for me. Can you give some extra-informations about de error, something like this :

- Which browser do you use ?
- Do you correctly copy and paste the code, and replacing discordWebhook var by your Discord Webhook link ?
- Does your browser have the correct library to use `replace();` (idk if the error comes from here, but maybe) ?

Maybe should I make a doc on my README.md to explain how it works, and revise the code for an english translation to avoid user's errors.

**Comment by FlamptX** [comment]
Nevermind I didn't know it had to be pasted in the console.

**Comment by Chaxiraxi** [comment]
NP, you prove that I have to make a doc for my script to not be used wrong. My bad
