### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by PaxMax-gif** [Chaxiraxi/Discord-Token-Grabber#2]
Hi I tested this code on safari and I entered the code (with the Webhook) and it restarted the discord without the information, how do I properly get this to work thank you.

**Comment by Chaxiraxi** [comment]
The correct way to do it is to paste the code into your browser's JavaScript console on the Discord web page. Once it's pasted, you just type enter, and it should reload Discord automatically and hack the current account by sending you the token and some other infos via your webhook. Note that I made my program in French, but even if you don't speak the language you should find easily all the infos like the token, the mail and the optional auto-login script. Don't worry

**Comment by PaxMax-gif** [comment]
Thank you so much for the help this made it much easier, thank you again
and have a great day.
