### ISSUE TITLE
how exactly do i use this?

### ISSUE THREAD

**Issue by NoStyle95** [Chaxiraxi/Discord-Token-Grabber#4]
??

**Comment by Chaxiraxi** [comment]
@NoStyle95 The victim have to open Discord in his browser, and paste the JavaScript code into the browser's console, and type enter. It should send through the webhook all his account infos, and his token

**Comment by NoStyle95** [comment]
well it would take some great social engineering skill to do that. is it possible to do it by just opening a word document?

**Comment by Chaxiraxi** [comment]
@NoStyle95 By doing like this, with word document containing a malicious VisualBasic macro, it would completely change the way to hack the account. Well, yes, it's possible, but not with my script. You gave me a great idea btw. Search for creating a malicious word macro, and hack the Discord account. Note that it will use a malware embedded in the word document, and it could be detected by antivirus

**Comment by NoStyle95** [comment]
please do this, it will be so much easier to trick people instead of opening an .exe

**Comment by Chaxiraxi** [comment]
@NoStyle95 To do this, I have to learn the basics of the VisualBasic language, which is used for word macros. It's a very messy programming language, and I have not a single base knowledge of how it works. Maybe in the future, and I'll post it in another GitHub repo.

Note that my main Discord account got banned few days ago for creating this script (it hurts) even if I never used it for illegal purposes. Take care with these kind of tools.

**Comment by JeffersonTan** [comment]
I had a great idea of possibly developing maybe some innocent front-end web application with this snuck inside the back-end JS, sounds viable but I dunno how it’ll work in practice, gotta learn that part.
But yeah I’m really interested about this

**Comment by Chaxiraxi** [comment]
@JeffersonTan I've already explored this way, and it seems impossible. Because to do this, you have to execute the malicious JS code directly on Discord, and for security reasons, any browser blocks opening new tabs or web pages with custom JavaScript there. But to improve social Engerinering, I made some time ago an edited version of this code that change the interface with custom CSS and changes the color of Discord. I didn't posted this edited version of my hack script, but if you want it, tell me and I'll maybe upload it in another branch

**Comment by SsouthSside99** [comment]
Upload

**Comment by Chaxiraxi** [comment]
@SsouthSside99 The victim have to open Discord in his browser, and paste the JavaScript code into the browser's console, and type enter. It should send through the webhook all his account infos, and his token

**Comment by Chaxiraxi** [comment]
@SsouthSside99 I'll put a reminder to upload it Tuesday afternoon if I find it on my hard drive
