### ISSUE TITLE
Is their a way to make this into a website? 

### ISSUE THREAD

**Issue by iqlessmemes** [Chaxiraxi/Discord-Token-Grabber#7]
If you could make it so they just have to click on a website to give you their token, that would be awesome.

**Comment by Chaxiraxi** [comment]
@iqlessmemes That's called an XSS attack, and Discord is a very well made website without this kind of vulnerability. Sorry dude

**Comment by iqlessmemes** [comment]
@Chaxiraxi so it's impossible to create malicious js code that runs in a website to steal the discord token?

**Comment by Chaxiraxi** [comment]
@iqlessmemes In an external website that is not Discord? Already tried, and nope. It's impossible due to cross-site security policies on the web browsers, and on Discord itself. You MUST run the javascript code directly ON discord. And this one is made to be run on the browser's console
